[package]
name = "hyxewave"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
workspace = "../"

[dependencies]
ctrlc = { version = "3.1.2", features = ["termination"] }
serde_json = "1.0.57"
serde = { version = "1.0.100", features = ["derive"] }
clap = "2.33.1"
bytes = "0.5.5"
env_logger = "0.7.1"
log = { version = "0.4.8", features = ["std", "max_level_trace", "release_max_level_info"] }
#tokio = { version = "0.2.22", features = ["full"] }
tokio = { version = "^1.2.0", features = ["full"] }
tokio-stream = "0.1.3"
tokio-util = { version = "^0.6.3", features = ["time"] }
futures-util = "0.3.12"
hyxe_net = { path = "../hyxe_net", version = "0.1.0" }
hyxe_user = { path = "../hyxe_user", version = "0.1.0" }
hyxe_crypt = { path = "../hyxe_crypt", version = "0.1.0" }
#rpassword = { path = "../rpassword", version = "4.0.5" }
#shrust = { path = "../shrust", version = "0.0.7" }
async-trait = "0.1.36"
colour = "*"
dirs = "*"
#crossterm = "0.17"
prettytable-rs = "0.8.0"
#tui = { version = "0.9.5", default-features = false, features = ['crossterm'] }
parking_lot = { version = "0.11.0", features = ["deadlock_detection"]}
lazy_static = "1.4.0"
#[target.'cfg(target_os = "windows")'.dependencies]
crossterm = { version = "0.18.0"}
#notifica = "2.0.0"
shutdown_hooks = "0.1.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
termion = "1.5.5"
nix = "*"

