[package]
name = "net2"
edition = "2018"
version = "0.2.33"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/net2-rs"
homepage = "https://github.com/rust-lang-nursery/net2-rs"
documentation = "https://doc.rust-lang.org/net2-rs/"
description = """
Extensions to the standard library's networking types as proposed in RFC 1158.
"""
[target.'cfg(any(target_os="redox", unix, target_os="wasi"))'.dependencies]
libc = "0.2.54"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = ["handleapi", "winsock2", "ws2def", "ws2ipdef", "ws2tcpip"] }

[dependencies]
cfg-if = "0.1"
futures = { version = "=0.3.0-alpha.19", features = ["compat", "async-await"], package = "futures-preview" }

[features]
nightly = []
duration = []
default = ["duration"]
