[package]
name = "firebase-rtdb"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3", features = ["native-tls-vendored", "json", "serde_json"] }
log = "0.4.8"
serde = { version = "1.0.126", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["full"] }
citadel_logging = { path = "../citadel_logging", version = "0.1.0" }