[package]
name = "online_order_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
tide = "0.16.0"
sqlx = { version = "0.5.9", features = [ "runtime-async-std-rustls", "sqlite", "macros", "time" ] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
dotenv = "0.15.0"
log = { version = "0.4.8", features = ["std", "max_level_info", "release_max_level_info"] }
anyhow = "1.0.51"
env_logger = "0.9.0"