name: flutterust
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^4.1.0
  retry: ^3.1.0
  background_fetch: ^1.0.0-nullsafety.1
  intl: ^0.17.0-nullsafety.2
  splashscreen: ^1.3.5
  firebase_core: ^1.0.1
  flutter_chat_bubble: ^1.0.2
  rxdart: ^0.26.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  cached_network_image: ^3.0.0-nullsafety
  firebase_messaging: ^9.0.0
  cupertino_icons: any
  optional: ^6.0.0-nullsafety.0
  quiver: ^3.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  flutter_easyloading: ^3.0.0
  crypt: ^4.0.1
  awesome_notifications:
    path: packages/awesome_notifications
  scrap:
    path: packages/scrap_ffi
  satori_ffi_parser:
    path: packages/satori_ffi_parser
  google_https_dns:
    path: packages/google_https_dns
  android_power_manager:
    path: packages/android_power_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #assets:
   # - assets/notification.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
