name: FireSaber
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1312
length-ciphertext: 1472
length-secret-key: 3040
length-shared-secret: 32
nistkat-sha256: 937d9b2e139112e13d4093a6afe715deff476e4d578208b9e8e1809de43835cd
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/commit/14ede83f1ff3bcc41f0464543542366c68b55871
