version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 2