name: "RAINBOW(256,68,36,36) - cyclic"
type: signature
claimed-nist-level: 3
length-public-key: 206744
length-secret-key: 511448
length-signature: 156
nistkat-sha256: 607fa94312778210c443431974087ce99357494ab16c8ad5a8418784b811223d
testvectors-sha256:  51559c38aefe636abd36094741be3b5f65de9e09cf9a5d37866b2e8d0eb58d22
principal-submitters:
  - Jintai Ding
auxiliary-submitters:
  - Ming-Shing Chen
  - Albrecht Petzoldt
  - Dieter Schmidt
  - Bo-Yin Yang
implementations:
    - name: clean
      version: https://github.com/fast-crypto-lab/rainbow-submission-round2/commit/af826fcb78f6af51a02d0352cff28a9690467bfd
