[package]
name = "hyxe_user"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
workspace = "../"
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
redis = ["redis-base", "mobc"]
default = ["single-threaded", "filesystem"]
sql = ["sqlx", "base64"]
filesystem = ["hyxe_crypt/filesystem", "tokio-util", "tokio-stream"]
multi-threaded = ["hyxe_crypt/multi-threaded"]
single-threaded = ["hyxe_crypt/single-threaded"]

# whenever an accountmanager is created, all accounts are purged when localhost-testing is enabled
localhost-testing = []
jwt-testing = []

[dependencies]
#futures-preview = { version = "=0.3.0-alpha.19", features = ["compat", "async-await"]}
serde = { version = "1.0.104", features=["rc", "derive"] }
serde_millis = "0.1.1"
tokio = "1.19.0"
async-trait = "^0.1.48"
futures = "0.3.5"
#future-parking_lot = { git = "https://github.com/nappa85/future-parking_lot" }
rand = "0.8.5"
multimap = "^0.8.3"
parking_lot = { version = "0.12.0", features = ["serde"] }
log = { version = "0.4.8" }
twox-hash = "1.6.3"
hyxe_crypt = { path = "../hyxe_crypt", version = "0.1.0", default-features=false }
serde_json = "1.0.62"
base64 = { version = "0.13.0", optional = true }
bytes = "1.0.1"
bstr = "0.2.15"
sqlx = { version = "0.5.11", features = ["all-databases", "runtime-tokio-native-tls"], optional = true }
redis-base = { package = "redis", version = "0.21.5", features = ["tokio-comp", "tokio-native-tls-comp"], optional=true }
mobc = { version = "0.7.3", optional = true }
firebase-rtdb = { path = "../firebase-rtdb", version = "0.1.0" }
jwt = { version = "0.16.0", features = ["openssl"] }
openssl = { version = "0.10.36", features = ["vendored"] }
uuid = { version = "1.0.0", features = ["v4"] }
bincode2 = "2.0.1"
chrono = "0.4.19"
tokio-util = { version = "0.7.2", features = ["net", "codec", "time", "io"], optional = true }
tokio-stream = { version = "0.1.7", optional = true }

[dev-dependencies]
tokio = { version = "1.19.0", features = ["macros"] }
lusna_logging = { path = "../lusna_logging", version = "0.1.0" }
dirs2 = "3.0.1"
rstest = "0.15.0"
lazy_static = "1.4.0"

ez_pqcrypto = { version = "0.1.1", path = "../ez_pqcrypto" }

[lib]
doctest = false