comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  range: "60..100"
  round: down
  precision: 4
  status:
    project:
      default:
        # basic
        target: 25%
        threshold: 1%
        # advanced settings
        #if_ci_failed: error
        informational: false
        only_pulls: true