codecov:
  disable_default_path_fixes: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  range: "80..90"
  round: down
  precision: 4
  status:
    project:
      default:
        # basic
        target: 70%
        # advanced settings
        #if_ci_failed: error
        informational: false
        only_pulls: true