version: '3.9'
services:
  client_a:
    environment:
      - CITADEL_SERVER_ADDR="172.16.238.12:25000"
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile
    networks:
      my_network:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
#  client_b:
#    build:
#      context: ./
#      dockerfile: ./docker/client/Dockerfile
#    networks:
#      my_network:
#        ipv4_address: 172.16.238.11
#    depends_on:
#      - server
  server:
    environment:
      - CITADEL_SERVER_ADDR="172.16.238.12:25000"
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    networks:
      my_network:
        ipv4_address: 172.16.238.12
  network:
    build:
      context: ./
      dockerfile: ./docker/network/Dockerfile
    networks:
      my_network:
        ipv4_address: 172.16.238.13
    privileged: true
networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24