[config]
default_to_workspace = false

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.pr]
dependencies = ["fmt", "clippy"]

[tasks.install-binstall]
command = "cargo"
args = ["install", "cargo-binstall"]

[tasks.install-nextest]
command = "cargo"
args = ["binstall", "cargo-nextest", "--secure", "-y"]
dependencies = ["install-binstall"]

[tasks.test-local]
command = "cargo"
description = "Tests all available unit/integration tests locally without using SQL/redis backends and appropriate localhost network settings"
env = { "SKIP_EXT_BACKENDS" = "true" }
args = ["nextest", "run", "--features", "localhost-testing"]
dependencies = ["install-nextest"]

[tasks.test]
command = "cargo"
description = "Tests all available unit/integration tests locally using SQL/redis backends and appropriate localhost network settings"
args = ["nextest", "run", "--features", "localhost-testing"]
dependencies = ["install-nextest"]

[tasks.install.mac]
command = "brew"
args = ["install", "llvm@13", "openssl", "cmake"]

[tasks.install.windows]
command = "set"
args = ["OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64"]
dependencies = ["install_deps"]

[tasks.install_deps.windows]
command = "choco"
args = ["install", "-y", "llvm", "openssl", "cmake"]