[package]
name = "net_sync"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.10.0", features = ["net", "macros", "rt", "time", "io-util"] }
futures = "0.3.16"
bytes = "1.0.1"
async-trait = "0.1.51"
parking_lot = "0.11.1"
bincode2 = "2.0.1"
serde = { version = "1.0.127", features = ["derive"] }
anyhow = "1.0.42"
tokio-util = { version = "0.6.7", features = ["codec"] }
rand = "0.8.4"

log = { version = "0.4.8", features = ["std", "max_level_info", "release_max_level_info"] }

[dev-dependencies]
env_logger = "0.7.1"
parking_lot = { version = "0.11.1", features = ["deadlock_detection"] }