[package]
name = "hyxe_util"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
workspace = "../"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[dependencies]
crossterm = "0.10.2"
lazy_static = "1.3.0"
#futures-preview = {version="0.3.0-alpha.17", features=["compat"]}
futures = "0.1.28"
tokio = "0.1.22"
tokio-net = "0.0.0"
tokio-core = "0.1.17"
parking_lot = { version = "0.9.0", features = ["nightly", "serde"] }
tokio-codec = "0.1.1"
multiqueue = "0.3.2"
bytes = "0.4.12"
zeroize = "0.9.2"
criterion = "0.2.11"
hashbrown = "0.6.0"

base64 = { path = "../base64", version = "0.10.1" }

[dev-dependencies]
criterion = "*"

[profile.bench]
debug = true

[[bench]]
name = "benchmarks"
harness = false