[package]
name = "scrap-ffi"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2021"

[lib]
name = "scrap_ffi"
crate-type = ["staticlib", "cdylib", "cdylib"]

[dependencies]
ffi_helpers = "0.2"
allo-isolate = "0.1.6"
hyxewave = { path = "../../../hyxewave", version = "0.1.0", default-features=false, features = ["enterprise"] }
parking_lot = "0.11.1"

android_logger = "0.9.0"
log = "0.4.8"

[build-dependencies]
cbindgen = "0.14.3"
dart-bindgen = "0.1.8"