[package]
name = "hyxe_wire"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
workspace = ".."
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
localhost-testing = []

[dependencies]
igd = { version = "^0.12.0", features = ["aio"] }
#tokio = { version = "^0.2.22", features = ["macros", "rt-util", "time", "net"] }
tokio = "1.18.2"
futures = "0.3.16"
async-trait = "0.1.36"
async-trait-with-sync = "0.1.36"
bytes = "^1.0.1"
byteorder = "1.3.4"
#rsntp = { version = "2.0.0", features = ["async"] }
parking_lot = "0.12.0"
stun = "0.4.2"
#socket2 = "0.4.1"
socket2 = { version = "0.4.4", features = ["all"] }
anyhow = "1.0.57"
serde = { version = "1.0.126", features = ["derive"] }
log = { version = "0.4.8", features = ["std"] }
bincode2 = "2.0.1"
async_ip = { path = "../async_ip", version = "0.1.0" }
itertools = "0.10.3"
quinn = { version = "0.8.2", features = ["rustls"] }
webpki = "0.21.0"
rustls = { version = "0.20.2", features = ["quic", "dangerous_configuration"] }
rustls-native-certs = "0.6.1"
rustls-pemfile = "1.0.0"
rcgen = "0.9.1"
openssl = { version = "0.10.36", features = ["vendored"] }
either = "1.6.1"
tokio-rustls = "0.23.2"
netbeam = { path = "../netbeam", version = "0.1.0" }
uuid = { version = "0.8.2", features = ["v4", "serde"] }

[target.'cfg(target_os = "windows")'.dependencies]
whoami = "1.2.1"

[dev-dependencies]
env_logger = "0.7.1"
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
rand = "0.8.4"
tokio-util = "0.6.7"
rstest = "0.12.0"

[lib]
doctest = false