name: LightSaber
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 672
length-ciphertext: 736
length-secret-key: 1568
length-shared-secret: 32
nistkat-sha256: dc2233ae221cfabbb1db5ab1a76c93967d37de9f87a8092561f95ab28eff6061
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/commit/14ede83f1ff3bcc41f0464543542366c68b55871
