[package]
name = "hyxewave_net"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[dependencies]
futures2 = { version = "=0.3.0-alpha.19", features = ["compat", "async-await"], package = "futures-preview" }
net2 = { path = "../net2-rs", version = "0.2.33" }
futures = "0.1.29"
tokio = "0.1.22"
tokio-tls = "0.3.0-alpha.6"
native-tls = "0.2.3"
tokio-threadpool = "0.1.15"
bytes = "0.4.12"
byteorder = "1.3.2"
base64 = { path = "../base64", version = "0.10.1" }
zerocopy = "0.2.7"
socket2 = "0.1.0"
async-std = "1.6.0-beta.2"
parking_lot = "0.9.0"
future-parking_lot = "0.3.2-alpha.2"
lazy_static = "1.4.0"
num = "0.2.0"
time = "0.1.42"
hashbrown = "0.6.0"
chashmap = "2.2.2"
secstr = "0.3.2"
vec_map = "0.8.1"

hyxe_netdata = { path = "../hyxe_shared", version = "0.1.0" }
hyxe_user = { path = "../hyxe_user", version = "0.1.0" }
hyxe_fs = { path = "../hyxe_fs", version = "0.1.0" }
hyxe_service = { path = "../hyxe_service", version = "0.1.0" }
hyxe_util = { path = "../hyxe_util", version = "0.1.0" }
hyxe_crypt = { path = "../hyxe_crypt", version = "0.1.0" }

rayon = "1.1.0"

[dev-dependencies]
criterion = "*"

[profile.bench]
debug = true

[[bench]]
name = "benchmarks"
harness = false