[package]
name = "dpb_kem"
version = "0.1.0"
edition = "2021"
workspace = ".."
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
