[package]
name = "lusna_ffi"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lusna_ffi"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.76"
jni = { version = "0.17.0", default-features = false }
hyxewave = { path = "../hyxewave", version = "0.1.0" }
#hyxe_net = { path = "../hyxe_net" }
lazy_static = "1.4.0"
android_logger = "0.9.0"
log = { version = "0.4.8", features = ["std", "max_level_trace", "release_max_level_trace"] }