sudo: false
language: rust
rust:
- stable
- nightly

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only nightly doc

after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo

addons:
  apt:
    packages:
      # Required for kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
  # override the default `--features unstable` used for the nightly branch (optional)
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: "gDbw39mo88DcDhqQocaJ4Yxs8x7nYzKE+uLE7I4ZYgtBt5j4a8vo2fsr5U3DwKRHplihiuUStAYqO2Qv1nBzhkAmdzSz1n1ljqdmIG+hZ9FwAITXcqrGSDcPGcFjhZn0TFC7PAufH/0jssatq4XgQBiFbiacPfWXq2xwUd6iaQArLNPXGfYXQytz6x31xdofJbJnffoUjgRN6DE1cUXt4n1Dmdq2gP1t61hqEXeBu0JwArrBm2V5IDXO4R+qhSkCsDwkhRC6w/pZ+C+HhH1wV/2EQuLXQ2Hrk3WpiWQ2jz/z7U3shWD0CWQ08rn9y5Hb0bmIhzo1Wvt4oiOmX2ERk5/UgqjGVsCMNboOKdtZzLKDX3dRn5amVK2KPZj9Ews+rZJDjFTsomobOLmK9fx9He68HS9ARVJAg0TXaQ8iWJfgCAMPK06QtAX3WfROPI4yN/QBi4WJIL6+2JhqjK/LU1BoDqEOAgrH+sAI2wcDJ3E1Uxr6SeF9FFzSPvf7Ga4lPXuv/P6qkHQ4xBn/eAz/MCUfP9UJzdSCPCDJfdQbvx1m2hrV+Lg/hIjegQtTADIf/wm5zyTYkW4egdrh/TSSkxYWCuLhh0+hRdJuNiVm8eGEhV3L1by3rb3qoaD9fcn1rL/ac2QHNT+JC+fG3+GmCN+JMa+K1U1U4XreY1CNArs="

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
