version: '3.9'
services:
  client_a:
    environment:
      CITADEL_SERVER_ADDR: "172.16.230.10:25000"
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
    networks:
      nat_network_a:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
      - nat_a
  server:
    environment:
      CITADEL_SERVER_ADDR: "172.16.230.10:25000"
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    networks:
      server_network:
        ipv4_address: 172.16.230.10
    depends_on:
      - nat_server
  nat_a:
    build:
      context: ../
      dockerfile: ./docker/nat/Dockerfile
      args:
        NAT_TYPE: ${NAT_TYPE_CLIENT_A:?err}
    networks:
      nat_network_a:
        ipv4_address: 172.16.238.254
      server_network:
    privileged: true
    cap_add:
      - NET_ADMIN
  nat_server:
    build:
      context: ../
      dockerfile: ./docker/nat/Dockerfile
      args:
        NAT_TYPE: "full_cone"
    networks:
      server_network:
        ipv4_address: 172.16.230.254
      nat_network_a:
    privileged: true
    cap_add:
      - NET_ADMIN
networks:
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.230.0/24
  nat_network_a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24