version: '3'
services:
  client_a:
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
    environment:
      CITADEL_SERVER_ADDR: "172.28.0.100:25000"
      STUN_0_ADDR: "172.28.0.10:3478"
      STUN_1_ADDR: "172.28.0.11:3478"
      STUN_2_ADDR: "172.28.0.12:3478"
      RUST_LOG: "citadel=trace"
      NAT_TYPE: ${NAT_TYPE_CLIENT_A:?err}
    entrypoint: ./set_nat.sh && client
    depends_on:
      - server
    networks:
      frontend:
    cap_add:
      - ALL
    privileged: true
  server:
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    environment:
      CITADEL_SERVER_ADDR: "172.28.0.100:25000"
      STUN_0_ADDR: "172.28.0.10:3478"
      STUN_1_ADDR: "172.28.0.11:3478"
      STUN_2_ADDR: "172.28.0.12:3478"
      RUST_LOG: "citadel=trace"
      NAT_TYPE: "full_cone"
    entrypoint: ./set_nat.sh && server
    depends_on:
      - stun0
      - stun1
      - stun2
    networks:
      frontend:
        ipv4_address: 172.28.0.100
    cap_add:
      - ALL
    privileged: true
  stun0:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.10
  stun1:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.11
  stun2:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.12
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16