version: '3.9'
services:
  client_a:
    environment:
      CITADEL_SERVER_ADDR: "172.16.238.12:25000"
      NAT_TYPE: ${NAT_TYPE_CLIENT_A:?err}
    build:
      context: ../
      dockerfile: ./docker/client/Dockerfile
    networks:
      nat_network:
        ipv4_address: 172.16.238.10
    depends_on:
      - server
    privileged: true
    cap_add:
      - NET_ADMIN
  server:
    environment:
      CITADEL_SERVER_ADDR: "172.16.238.12:25000"
      NAT_TYPE: "full_cone"
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    networks:
      nat_network:
        ipv4_address: 172.16.238.12
    privileged: true
    cap_add:
      - NET_ADMIN
networks:
  nat_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24