version: '3'
services:
  client_a:
    image: ubuntu:latest
    depends_on:
      - server
    networks:
      - frontend
      - backend
    cap_add:
      - NET_ADMIN
    privileged: true
    command: sh -c "apt-get update && apt-get install -y iptables inetutils-ping; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ping -c 3 server"
  server:
    image: ubuntu:latest
    networks:
      backend:
        ipv4_address: 172.29.0.10
    cap_add:
      - NET_ADMIN
    privileged: true
    entrypoint: sh -c "apt-get update && apt-get install -y iptables inetutils-ping; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -A FORWARD -j ACCEPT; iptables -t nat -A PREROUTING -i eth1 -j REDIRECT; sleep infinity"
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
  stun0:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  stun1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
  stun2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16