version: '3'
services:
  peer_a:
    build:
      context: ../
      dockerfile: ./docker/peer/Dockerfile
    entrypoint: ["/usr/src/peer/exec.sh"]
    environment:
      CITADEL_SERVER_ADDR: "172.28.0.100:25000"
      MY_PEER_ID: "peer_a"
      OTHER_PEER_ID: "peer_b"
      DO_EXIT: "true" # collect the exit code from this peer
      STUN_0_ADDR: "172.28.0.10:3478"
      STUN_1_ADDR: "172.28.0.11:3478"
      STUN_2_ADDR: "172.28.0.12:3478"
      RUST_LOG: "citadel=trace"
      NAT_TYPE: ${NAT_TYPE_PEER_A:?err}
    depends_on:
      - server
    networks:
      frontend:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - ALL
    privileged: true
  peer_b:
    build:
      context: ../
      dockerfile: ./docker/peer/Dockerfile
    entrypoint: ["/usr/src/peer/exec.sh"]
    environment:
      CITADEL_SERVER_ADDR: "172.28.0.100:25000"
      MY_PEER_ID: "peer_b"
      OTHER_PEER_ID: "peer_a"
      DO_EXIT: "false" # do not collect the exit code from this peer
      STUN_0_ADDR: "172.28.0.10:3478"
      STUN_1_ADDR: "172.28.0.11:3478"
      STUN_2_ADDR: "172.28.0.12:3478"
      RUST_LOG: "citadel=trace"
      NAT_TYPE: ${NAT_TYPE_PEER_B:?err}
    depends_on:
      - server
    networks:
      frontend:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - ALL
    privileged: true
  server:
    build:
      context: ../
      dockerfile: ./docker/server/Dockerfile
    entrypoint: ["/usr/src/server/exec.sh"]
    environment:
      CITADEL_SERVER_ADDR: "172.28.0.100:25000"
      STUN_0_ADDR: "172.28.0.10:3478"
      STUN_1_ADDR: "172.28.0.11:3478"
      STUN_2_ADDR: "172.28.0.12:3478"
      EMPTY_KERNEL: "true" # use an empty server kernel
      RUST_LOG: "citadel=trace"
      NAT_TYPE: "full_cone"
    depends_on:
      - stun0
      - stun1
      - stun2
    networks:
      frontend:
        ipv4_address: 172.28.0.100
    dns:
      - 8.8.8.8
      - 8.8.4.4
    cap_add:
      - ALL
    privileged: true
  stun0:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.10
  stun1:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.11
  stun2:
    image: coturn/coturn:4.6.1-debian
    networks:
      frontend:
        ipv4_address: 172.28.0.12
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16