name: Dilithium4
type: signature
claimed-nist-level: 3
length-public-key: 1760
length-secret-key: 3856
length-signature: 3366
nistkat-sha256: 87844f967b4340d60dc4d83aac0f1d3a244fa8f9490017f72fd4969bba168f88
testvectors-sha256: 91087880c84678bf66008d843e7fa1ab5231114a8ca9e9e36c41065f14172af2
principal-submitters:
  - Vadim Lyubashevsky
auxiliary-submitters:
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/dilithium/commit/c1b40fd599e71f65aa18be64dd6c3fc8e84b0c08
    - name: avx2
      version: https://github.com/pq-crystals/dilithium/commit/c1b40fd599e71f65aa18be64dd6c3fc8e84b0c08
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Darwin
                - Linux
            required_flags:
                - avx2
                - bmi2
