[package]
name = "lock_wrapper"
version = "0.1.0"
edition = "2021"
workspace = ".."
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = [
    "parking_lot"
]

wasm = []

[dependencies]
parking_lot = { version = "0.12.1", default-features = false, optional = true }