[package]
name = "igd"
version = "0.11.1"
edition = "2018"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
description = "Internet Gateway Protocol client"
homepage = "https://github.com/sbstp/rust-igd"
repository = "https://github.com/sbstp/rust-igd"
documentation = "https://docs.rs/igd/"
readme = "README.md"
keywords = ["igd", "upnp"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
xmltree = "0.10"
rand = "0.7"
attohttpc = { version = "0.10", default-features = false }
url = "2"
log = "0.4"
futures = { version = "0.3", optional = true }
tokio = { version = "0.2", optional = true, features = [ "udp", "macros" ]}
bytes = { version = "0.5", optional = true }
http = {version = "0.2", optional = true }

[dependencies.hyper]
version = "0.13"
default-features = false
features = [ "runtime" ]
optional = true

[dev-dependencies]
simplelog = "0.7"

[features]
default = []
aio = ["futures", "tokio", "hyper", "bytes", "http"]

[[example]]
name = "add_any_port"

[[example]]
name = "add_port"

[[example]]
name = "add_remove"

[[example]]
name = "aio"
required-features = ["aio"]

[[example]]
name = "external_ip"

[[example]]
name = "remove_port"
