[package]
name = "citadel_pqcrypto"
version = "0.1.1"
authors = ["Thomas Braun <thomas.braun@avarok.net>"]
edition = "2021"
homepage = "https://avarok.net/"
repository = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol"
readme = "../README.md"
categories = ["cryptography", "post-quantum", "quantum", "network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[features]
default = ["std"]
std = [
    "serde/std",
    "aes-gcm-siv/std",
    "aes-gcm-siv/alloc",
    "chacha20poly1305/alloc",
    "chacha20poly1305/std",
    "bytes/std",
    "strum/std",
    "kyber-pke/std",
    "pqcrypto-falcon-wasi/std",
    "pqcrypto-traits-wasi/std",
    "rand/std",
    "sha3/std"
]

wasm = ["kyber-pke/wasm", "lazy_static/spin_no_std"]

[dependencies]
generic-array = { version = "0.14.6", features = ["serde"]}
lazy_static = { default-features = false, version = "1.4.0" }
enum_primitive = { default-features = false, version = "0.1.1" }
serde = { version = "1.0.152", default-features = false, features = ["derive", "rc"] }
bincode2 = { default-features = false, version = "2.0.1" }
aes-gcm-siv = { version = "0.11.1", default-features = false, features = ["heapless", "aes", "alloc"]}
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["heapless", "alloc"] }
bytes = { version = "1.3.0", default-features = false }
parking_lot = { version = "0.12.1", features = ["serde"] }
log = { default-features = false, version = "0.4.17" }
strum = { version = "0.24.1", default-features = false, features = ["derive"] }
sha3 = { version = "0.10", default-features = false }
kyber-pke = { git = "https://github.com/Avarok-Cybersecurity/kyber-pke", default-features = false, branch = "master", features=["90s"] }
packed_struct = { version = "0.10.1", features = ["serde"] }
rand = { version = "0.8.5", default-features = false }
getrandom = { version = "*", default-features = false, features = ["js"], optional = true }
serde-big-array = { default-features = false, version = "0.4.1"}

[target.'cfg(not(target_family = "wasm"))'.dependencies]
oqs = { version = "0.7.2", default-features = false, features = ["serde", "falcon"] }

[target.'cfg(target_family = "wasm")'.dependencies]
pqcrypto-falcon-wasi = { version = "0.2.14", default-features=false, features = ["serialization", "avx2"] }
pqcrypto-traits-wasi = { version = "0.3.4", default-features = false }

[dev-dependencies]
citadel_logging = { path = "../citadel_logging", version = "0.1.0" }

[lib]
doctest = false
