language: rust

rust:
  - stable
  - beta
  - nightly
  
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

env:
  matrix:
    - RSNTP_FEATURE_FLAGS=""
    - RSNTP_FEATURE_FLAGS="--no-default-features"

script:
  - cargo build --verbose $RSNTP_FEATURE_FLAGS
  - cargo test --verbose $RSNTP_FEATURE_FLAGS