[package]
name = "lusna_sdk"
version = "0.1.0"
edition = "2018"
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["filesystem"]
filesystem = ["hyxe_net/filesystem", "dirs2"]
multi-threaded = ["hyxe_net/multi-threaded"]
sql = ["hyxe_net/sql"]
redis = ["hyxe_net/redis"]
webrtc = ["hyxe_net/webrtc"]

# for testing only
localhost-testing = ["hyxe_net/localhost-testing", "tracing"]
localhost-testing-assert-no-proxy = ["hyxe_net/localhost-testing-assert-no-proxy"]

[dependencies]
hyxe_net = { path = "../hyxe_net", default-features = false }
tokio = { version = "1.20.1", features = ["full"] }
futures = "0.3.19"
parking_lot = "0.12.0"
log = "0.4.8"
lazy_static = "1.4.0"
uuid = { version = "1.0.0", features = ["v4"] }
dirs2 = { version = "3.0.1", optional = true }
tracing = { git = "https://github.com/tokio-rs/tracing.git", branch = "v0.1.x", optional = true }

[dev-dependencies]
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
dirs2 = "3.0.1"
lusna_logging = { path = "../lusna_logging", version = "0.1.0" }
rstest = { git = "https://github.com/la10736/rstest", branch="master" }
serde = { version = "1.0.137", features = ["derive"] }
rand = "0.8.5"

[lib]
doctest = false

[package.metadata.cargo-all-features]

# Features "foo" and "bar" are incompatible, so skip permutations including them
#skip_feature_sets = [
#    ["single-threaded", "multi-threaded"],
#    ["multi-threaded", "single-threaded"]
#]

# If your crate has a large number of optional dependencies, skip them for speed
skip_optional_dependencies = false

# Add back certain optional dependencies that you want to include in the permutations
#extra_features = [
#    "log",
#]

# Exclude certain features from the build matrix
#denylist = ["foo", "bar"]

# Only include certain features in the build matrix
#(incompatible with `denylist`, `skip_optional_dependencies`, and `extra_features`)
#allowlist = ["foo", "bar"]