[package]
name = "lusna_sdk"
version = "0.1.0"
edition = "2018"
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["plus"]
standard = ["hyxe_net/single-threaded"]
plus = ["hyxe_net/multi-threaded"]
enterprise-lite = ["hyxe_net/single-threaded", "hyxe_net/enterprise"]
enterprise = ["hyxe_net/multi-threaded", "hyxe_net/enterprise"]
webrtc = ["hyxe_net/webrtc"]

# for testing only
localhost-testing = ["hyxe_net/localhost-testing"]
localhost-testing-assert-no-proxy = ["hyxe_net/localhost-testing-assert-no-proxy"]

[dependencies]
hyxe_net = { path = "../hyxe_net", default-features = false }
tokio = { version = "1.19.0", features = ["full"] }
futures = "0.3.19"
parking_lot = "0.12.0"
log = { version = "0.4.14", features = ["std"] }
env_logger = "0.9.0"
lazy_static = "1.4.0"
uuid = { version = "1.0.0", features = ["v4"] }

[dev-dependencies]
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
dirs2 = "3.0.1"
env_logger = "0.9.0"
rstest = { git = "https://github.com/la10736/rstest", branch="master" }
serde = { version = "1.0.137", features = ["derive"] }
rand = "0.8.5"

[lib]
doctest = false
