[package]
name = "async_ip"
version = "0.1.0"
authors = ["Thomas Braun <braunth@oregonstate.edu>"]
edition = "2018"
description = "An asynchronous client used to obtain one's global Ipv6 or Ipv4 address"
readme = "README.md"
homepage = "https://thomaspbraun.com/"
repository = "https://github.com/tbraun96/async_ip"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.1"

[dev-dependencies]
tokio = "0.2.11"