[package]
name = "ez_pqcrypto"
version = "0.1.1"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
description = "Abstracts over pqcrypto. Allows selecting a post-quantum KEM algorithm by setting a single byte-sized value. Useful for multi-algorithmic or nondeterministic schemes"
readme = "README.md"
homepage = "https://thomaspbraun.com/"
repository = "https://github.com/tbraun96/ez_pqcrypto/"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[features]
default = ["aes"]
unordered = ["circular-queue", "parking_lot"]
aes = ["aes-gcm-siv"]
chacha20 = ["chacha20poly1305"]

[dependencies]
pqcrypto = { path = "./pqcrypto/pqcrypto" }
nanoserde = "0.1.16"
rand = "0.7.3"
aes-gcm-siv = { version = "0.5.0", features = ["heapless"], optional = true }
chacha20poly1305 = { version = "*", features = ["heapless", "xchacha20poly1305"], optional = true }
bytes = "0.5.6"
circular-queue = { version = "*", optional = true }
parking_lot = { version = "0.11.0", optional = true }