[package]
name = "ez_pqcrypto"
version = "0.1.1"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
description = "Abstracts over pqcrypto. Allows selecting a post-quantum KEM algorithm by setting a single byte-sized value. Useful for multi-algorithmic or nondeterministic schemes"
readme = "README.md"
homepage = "https://thomaspbraun.com/"
repository = "https://github.com/tbraun96/ez_pqcrypto/"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[features]
default = ["unordered"]
unordered = ["circular-queue", "parking_lot"]

[dependencies]
pqcrypto-traits = "*"
pqcrypto-saber = "*"
pqcrypto-kyber = "*"
pqcrypto-ntru = "*"
enum_primitive = "0.1.1"
serde = { version = "1.0.118", features = ["derive"] }
bincode2 = "2.0.1"
aes-gcm-siv = { version = "*", features = ["heapless"]}
chacha20poly1305 = { version = "*", features = ["heapless", "xchacha20poly1305"] }
bytes = "^1.0.1"
circular-queue = { version = "*", features = ["serde_support"], optional = true }
parking_lot = { version = "0.11.0", features = ["serde"], optional = true }
log = { version = "0.4.8", features = ["std", "max_level_info", "release_max_level_info"] }
env_logger = "0.8.3"
#oqs = { version = "^0.5.0", default-features = false, features = ["minimal"] }

[dev-dependencies]
rand = "0.7.3"