[package]
name = "pqcrypto"
description = "Post-Quantum cryptographic primitives"
readme = "README.md"
version = "0.10.0"
authors = ["Thom Wiggers <thom@thomwiggers.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rustpq/"
repository = "https://github.com/rustpq/pqcrypto/"
keywords = ["cryptography", "post-quantum", "security"]
categories = ["cryptography"]
workspace = "../../../"

[dependencies]
pqcrypto-traits = { path = "../pqcrypto-traits", version = "0.3.2" }
#pqcrypto-kyber = { path = "../pqcrypto-kyber", version = "0.6.5" }
#pqcrypto-frodo = { path = "../pqcrypto-frodo", version = "0.4.2" }
#pqcrypto-ntru = { path = "../pqcrypto-ntru", version = "0.4.2" }
pqcrypto-saber = { path = "../pqcrypto-saber", version = "0.1.3" }
#pqcrypto-ledacryptkem = { path = "../pqcrypto-ledacryptkem", version = "0.0.3" }
#pqcrypto-threebears = { path = "../pqcrypto-threebears", version = "0.2.0" }
#pqcrypto-classicmceliece = { path = "../pqcrypto-classicmceliece", version = "0.1.0" }
#pqcrypto-newhope = { path = "../pqcrypto-newhope", version = "0.1.2" }
#pqcrypto-hqc = { path = "../pqcrypto-hqc", version = "0.0.1" }
#pqcrypto-mqdss = { path = "../pqcrypto-mqdss", version = "0.2.3" }
#pqcrypto-dilithium = { path = "../pqcrypto-dilithium", version = "0.3.1" }
#pqcrypto-falcon = { path = "../pqcrypto-falcon", version = "0.2.2" }
#pqcrypto-qtesla = { path = "../pqcrypto-qtesla", version = "0.1.1" }
#pqcrypto-rainbow = { path = "../pqcrypto-rainbow", version = "0.1.2" }
#pqcrypto-sphincsplus = { path = "../pqcrypto-sphincsplus", version = "0.5.0" }

[badges]
travis-ci = { repository = "rustpq/pqcrypto", branch = "master" }
maintenance = { status = "actively-developed" }