[package]
name = "quantum_random"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
homepage = "https://github.com/tbraun96/quantum_random"
description = "This is the rust implementation of the ANU Quantum Random Number System. You can easily generate an arbitrary number of u8's, u16's, u32's, u64's, and u128's"
readme = "README.md"
license-file = "LICENSE"
# For deployment on crates.io
exclude = [
    "./target/*"
]

[dependencies]
reqwest = "0.9.19"
futures-preview = { version= "0.3.0-alpha.19", features = ["async-await", "compat"]}
rand = "0.6.5"
rayon = "1.1.0"
parking_lot = {version = "0.9.0", features = ["nightly", "serde"]}
serde = "1.0.92"
dirs-2 = "1.1.0"
bincode = "1.2.1"
byteorder = "1.3.1"
lazy_static = "1.3.0"
mut_static = "5.0.0"
chrono = {version = "0.4.6", features = ["serde"]}