name: LEDAKEMLT32
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 12032
length-secret-key: 66
length-ciphertext: 12064
length-shared-secret: 48
nistkat-sha256: b8b17dbb77aa3c3c77f738be053b355185388859ae6baa5655bf7e8413020b7f
principal-submitters:
  - Marco Baldi
auxiliary-submitters:
  - Alessandro Barenghi
  - Franco Chiaraluce
  - Gerardo Pelosi
  - Paolo Santini
implementations:
  - name: leaktime
    version: 2.1
