// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of client-to-server connection.
 *
 * Used for C2S disconnect events and peer discovery requests.
 * For P2P connections, use [`PeerConnectionType`] instead.
 *
 * # Variants
 *
 * - `Server`: Standard client-to-server connection (most common)
 * - `Extended`: Connection through federated server network (future feature)
 *
 * # Network Topology
 *
 * ```text
 * Standard Mode:          Extended Mode:
 * ┌────────┐              ┌────────┐      icid        ┌────────┐
 * │ Client │◄─────────────│ Server │◄────────────────►│ Server │
 * └────────┘  session_cid └────────┘                  └────────┘
 * ```
 */
export type ClientConnectionType = { "Server": { 
/**
 * The session CID for this connection
 */
session_cid: bigint, } } | { "Extended": { 
/**
 * The session CID for the client's connection to their home server
 */
session_cid: bigint, 
/**
 * The interserver connection identifier (icid) for server-to-server link
 */
interserver_cid: bigint, } };
