// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * If force_login is true, the protocol will disconnect any previously existent sessions in the session manager attributed to the account logging-in (so long as login succeeds)
 * The default is a Standard login that will with force_login set to false
 */
export type ConnectMode = { "Standard": { force_login: boolean, } } | { "Fetch": { force_login: boolean, } };
