// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptionAlgorithm } from "./EncryptionAlgorithm";
import type { KemAlgorithm } from "./KemAlgorithm";
import type { SigAlgorithm } from "./SigAlgorithm";

export type CryptoParameters = { encryption_algorithm: EncryptionAlgorithm, kem_algorithm: KemAlgorithm, sig_algorithm: SigAlgorithm, };
