// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncryptionAlgorithm = "AES_GCM_256" | "ChaCha20Poly_1305" | "KyberHybrid" | "Ascon80pq";
