// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The default error type for this crate
 */
export type Error = "SharedSecretNotLoaded" | "EncryptionFailure" | "DecryptionFailure" | { "Generic": string } | { "Other": string } | "InvalidLength" | "UnsupportedAlgorithm";
