// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a factor is derived from.
 */
export type FactorKind = "Password" | "SecurityKey" | "RecoveryCode";
