// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupType } from "./GroupType";

/**
 * Options for creating message groups
 */
export type MessageGroupOptions = { group_type: GroupType, id: bigint, };
