// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This is to replace a tuple for greater organization
 */
export type MutualPeer = { 
/**
 * The interserver cid to which `cid` belongs to
 */
parent_icid: bigint, 
/**
 * the client to which belongs within `parent_icid`
 */
cid: bigint, 
/**
 * The username of this peer
 */
username: string | null, };
