// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ObjectTransferOrientation = { "Receiver": { is_revfs_pull: boolean, } } | "Sender";
