// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VirtualObjectMetadata } from "./VirtualObjectMetadata";

export type ObjectTransferStatus = "TransferBeginning" | { "ReceptionBeginning": [string, VirtualObjectMetadata] } | { "TransferTick": [number, number, number] } | { "ReceptionTick": [number, number, number] } | "TransferComplete" | "ReceptionComplete" | { "Fail": string };
