// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of peer-to-peer connection.
 *
 * Used in peer signaling to identify P2P connections between clients.
 *
 * # Variants
 *
 * - `LocalGroupPeer`: Both peers connected to the same server
 * - `ExternalGroupPeer`: Peers connected to different servers (federated)
 */
export type PeerConnectionType = { "LocalGroupPeer": { 
/**
 * This client's session CID
 */
session_cid: bigint, 
/**
 * The peer's CID
 */
peer_cid: bigint, } } | { "ExternalGroupPeer": { 
/**
 * This client's session CID
 */
session_cid: bigint, 
/**
 * The interserver connection identifier
 */
interserver_cid: bigint, 
/**
 * The peer's CID on their home server
 */
peer_cid: bigint, } };
