// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Contains info about a peer, used for giving the user access to usernames and names of peers
 */
export type PeerInfo = { 
/**
 * the client to which belongs within `parent_icid`
 */
cid: bigint, 
/**
 * The username of this peer
 */
username: string, 
/**
 * The full name of this peer
 */
full_name: string, };
