// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provides the enumeration for all security levels
 */
export type SecurityLevel = "Standard" | "Reinforced" | "High" | "Ultra" | "Extreme" | { "Custom": number };
