// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a session that has signed in may do.
 */
export type SessionScope = "Full" | "Recovery";
