// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoParameters } from "./CryptoParameters";
import type { HeaderObfuscatorSettings } from "./HeaderObfuscatorSettings";
import type { SecrecyMode } from "./SecrecyMode";
import type { SecurityLevel } from "./SecurityLevel";

export type SessionSecuritySettings = { security_level: SecurityLevel, secrecy_mode: SecrecyMode, crypto_params: CryptoParameters, header_obfuscator_settings: HeaderObfuscatorSettings, };
