// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignInCredential } from "./SignInCredential";
import type { SignInPolicy } from "./SignInPolicy";

/**
 * What a [`SignInManagementOp`] that the server carried out returns to the application.
 */
export type SignInManagementOutcome = { "Credentials": { policy: SignInPolicy, credentials: Array<SignInCredential>, } } | { "Added": { id: number, } } | "Renamed" | "Removed" | "PolicySet" | { "RecoveryCodes": Array<string> };
