// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which factors a sign-in must prove.
 */
export type SignInPolicy = "Password" | "PasswordAndKey" | "KeyOnly";
