// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FactorKind } from "./FactorKind";

/**
 * One enrolled factor, as `ListCredentials` reports it.
 */
export type SignInCredential = { id: number, kind: FactorKind, label: string, 
/**
 * The WebAuthn credential id, for a security key.
 */
credential_id: Array<number> | null, created_ms: bigint, last_used_ms: bigint | null, 
/**
 * A recovery code that has been used. It can never sign in again.
 */
consumed: boolean, };
