// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignInPolicy } from "./SignInPolicy";

/**
 * A change to an account's sign-in factors. Each one needs a fresh proof of the account's
 * factors (a step-up), except the two a recovery session may make.
 */
export type SignInManagementOp = "ListCredentials" | { "AddSecurityKey": { credential_id: Array<number>, label: string, } } | { "RenameCredential": { id: number, label: string, } } | { "RemoveCredential": { id: number, } } | { "SetSignInPolicy": { policy: SignInPolicy, } } | "RegenerateRecoveryCodes";
