// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityLevel } from "./SecurityLevel";

export type TransferType = "FileTransfer" | { "RemoteEncryptedVirtualFilesystem": { virtual_path: string, security_level: SecurityLevel, } };
