// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A convenience wrapper for passing arguments to functions that require searches for a user
 */
export type UserIdentifier = { "ID": bigint } | { "Username": string };
