// Auto-generated by scripts/inject-versions.js - DO NOT EDIT
// Generated at: 2026-09-30T15:39:09.304Z

/**
 * Returns the Citadel Protocol version.
 *
 * This version is extracted from citadel_proto/src/constants.rs
 * (MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION).
 *
 * @returns Semantic version string (e.g., "0.9.0")
 */
export function protocol_version(): string {
  return "0.11.0";
}

/**
 * Returns the Citadel SDK version.
 *
 * This version is extracted from citadel_sdk/Cargo.toml.
 *
 * @returns Semantic version string (e.g., "0.13.0")
 */
export function sdk_version(): string {
  return "0.14.0";
}
