// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectId } from "./ObjectId";
import type { TransferType } from "./TransferType";

export type VirtualObjectMetadata = { name: string, date_created: string, author: string, plaintext_length: number, group_count: number, object_id: ObjectId, cid: bigint, transfer_type: TransferType, };
