// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified type representing all possible virtual connections.
 *
 * This type is used throughout the protocol for packet routing and connection
 * management. It covers both C2S and P2P connection scenarios.
 *
 * # Variants
 *
 * ## C2S Connections
 * - `LocalGroupServer`: Client connected to their home server
 * - `ExternalGroupServer`: Client connected through federated network (future)
 *
 * ## P2P Connections
 * - `LocalGroupPeer`: P2P where both peers share the same server
 * - `ExternalGroupPeer`: P2P across federated servers (future)
 */
export type VirtualConnectionType = { "LocalGroupPeer": { 
/**
 * This client's session CID
 */
session_cid: bigint, 
/**
 * The peer's CID
 */
peer_cid: bigint, } } | { "ExternalGroupPeer": { 
/**
 * This client's session CID
 */
session_cid: bigint, 
/**
 * The interserver connection identifier
 */
interserver_cid: bigint, 
/**
 * The peer's CID on their home server
 */
peer_cid: bigint, } } | { "LocalGroupServer": { 
/**
 * The session CID
 */
session_cid: bigint, } } | { "ExternalGroupServer": { 
/**
 * This client's session CID
 */
session_cid: bigint, 
/**
 * The interserver connection identifier
 */
interserver_cid: bigint, } };
