[package]
name = "netbeam"
version = "0.7.0"
description = "a pure-rust asynchronous network synchronization crate (using tokio) that recreates familiar asynchronous paradigms but in a network context"
authors = ["Thomas Braun <thomas.braun@avarok.net>"]
edition = "2021"
workspace = ".."
homepage = "https://avarok.net/"
repository = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol"
readme = "../README.md"
categories = ["cryptography", "network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = [
    "rand/std",
    "rand/std_rng",
    "citadel_io/std",
    "anyhow/std"
]
wasm = [
    "citadel_io/wasm"
]

[dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "io-util"] }
citadel_io = { workspace = true }
futures = { workspace = true, features = ["std"] }
bytes = { workspace = true }
async-trait = { workspace = true }
bincode2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
rand = { workspace = true }
async-stream = { workspace = true }
sync_wrapper = { workspace = true}
log = { workspace = true }

[dev-dependencies]
async-recursion = { workspace = true }
citadel_logging = { workspace = true }
rstest = { workspace = true }

[lib]
doctest = false
