[package]
name = "netbeam"
version = "0.1.0"
description = "a pure-rust asynchronous network synchronization crate (using tokio) that recreates familiar asynchronous paradigms but in a network context"
license = "MIT"
repository = "https://github.com/tbraun96/netbeam"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
tokio = { version = "=1.20.1", features = ["net", "macros", "rt", "time", "io-util", "parking_lot"] }
futures = "0.3.16"
bytes = "1.0.1"
async-trait = "0.1.51"
parking_lot = "0.12.0"
bincode2 = "2.0.1"
serde = { version = "1.0.127", features = ["derive"] }
anyhow = "1.0.57"
tokio-util = { version = "0.7.3", features = ["codec"] }
rand = "0.8.4"
async-stream = "0.3.2"

log = "0.4.8"

[dev-dependencies]
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
async-recursion = "1.0.0"
citadel_logging = { path = "../citadel_logging", version = "0.1.0" }
rstest = "0.15.0"

[lib]
doctest = false