[package]
name = "citadel_user"
version = "0.1.0"
authors = ["Thomas Braun <tbraun96@gmail.com>"]
edition = "2018"
workspace = "../"
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["filesystem", "std"]
redis = ["redis-base", "mobc"]
sql = ["sqlx", "base64", "itertools"]
filesystem = ["citadel_crypt/filesystem", "tokio-util", "tokio-stream"]
std = [
    "citadel_crypt/std",
    "tokio/fs",
    "rand/std",
    "sha3/std"
]
wasm = ["citadel_crypt/wasm"]
google-services = ["openssl", "jwt", "firebase-rtdb"]

# whenever an accountmanager is created, all accounts are purged when localhost-testing is enabled
localhost-testing = []
jwt-testing = []

[dependencies]
#futures-preview = { version = "=0.3.0-alpha.19", features = ["compat", "async-await"]}
itertools = { version = "0.10.5", optional = true }
serde = { version = "1.0.104", features=["rc", "derive"] }
serde_millis = "0.1.1"
tokio = { version = "1.23.0", default-features = false, features = ["io-util"] }
async-trait = "^0.1.48"
futures = "0.3.5"
#future-parking_lot = { git = "https://github.com/nappa85/future-parking_lot" }
rand = { version = "0.8.5", default-features = false }
multimap = "^0.8.3"
parking_lot = { version = "0.12.0", features = ["serde"] }
log = { version = "0.4.8" }
twox-hash = "1.6.3"
sha3 = { version = "0.10", default-features = false }
citadel_crypt = { path = "../citadel_crypt", version = "0.1.0", default-features=false }
serde_json = "1.0.62"
base64 = { version = "0.13.0", optional = true }
bytes = "1.0.1"
bstr = "0.2.15"
sqlx = { version = "0.5.11", features = ["all-databases", "runtime-tokio-native-tls"], optional = true }
redis-base = { package = "redis", version = "0.21.5", features = ["tokio-comp", "tokio-native-tls-comp"], optional=true }
mobc = { version = "0.7.3", optional = true }
firebase-rtdb = { path = "../firebase-rtdb", version = "0.1.0", optional = true }
jwt = { version = "0.16.0", features = ["openssl"], optional = true }
openssl = { version = "0.10.36", features = ["vendored"], optional = true }
uuid = { version = "1.0.0", features = ["v4"] }
bincode2 = "2.0.1"
chrono = "0.4.20"
tokio-util = { version = "0.7.2", default-features = false, features = ["io"], optional = true }
tokio-stream = { version = "0.1.7", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["macros"] }
citadel_logging = { path = "../citadel_logging", version = "0.1.0" }
dirs2 = "3.0.1"
rstest = "0.16.0"
lazy_static = "1.4.0"

citadel_pqcrypto = { version = "0.1.1", path = "../citadel_pqcrypto" }

[lib]
doctest = false