[package]
name = "citadel_crypt"
version = "0.4.0"
authors = ["Thomas Braun <thomas.braun@avarok.net>"]
description = "Higher-level cryptographic library for the Citadel Protocol"
edition = "2021"
workspace = ".."
homepage = "https://avarok.net/"
repository = "https://github.com/Avarok-Cybersecurity/Citadel-Protocol"
readme = "../README.md"
categories = ["cryptography", "post-quantum", "quantum", "network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "./target/*"
]

[features]
default = ["filesystem", "std"]
filesystem = []
std = [
    "citadel_pqcrypto/std",
    "byteorder/std",
    "rand/std",
    "tokio/default",
    "citadel_io/std",
    "rust-argon2/default"
]
wasm = [
    "citadel_pqcrypto/wasm",
    "citadel_io/wasm"
]

[dependencies]
async-trait = { default-features = false, version = "0.1.61" }
bincode2 = { default-features = false, version = "2.0.1" }
serde = { version="1.0.152", default-features = false, features=["rc", "derive"] }
futures = { version = "0.3.25", default-features = false }
log = { default-features = false, version = "0.4.17" }
byteorder = { version = "1.4.3", default-features=false }
bytes = { version = "^1.3.0", features = ["serde"] }
num-integer = { default-features = false, version = "0.1.45" }
rand = { version = "0.8.5", default-features = false }
arrayvec = { version = "0.7.2", default-features = false, features = ["serde"] }
citadel_pqcrypto = { path = "../citadel_pqcrypto", version = "0.4.0", default-features = false }
citadel_io = { path = "../citadel_io", version = "0.4.0", default-features = false }
bitvec = { default-features = false, version = "1.0.1", features = ["alloc"] }
serde-big-array = { default-features = false, version = "0.5.0"}
rust-argon2 = { version = "1.0.0", default-features = false }
tokio = { version = "1.24", default-features=false, features = ["rt", "macros", "time"] }
sha3 = { default-features = false, version = "0.10.6" }
tokio-stream = { default-features = false, version = "0.1.11" }
auto_impl = { default-features = false, version = "1.0.1" }
zeroize = { default-features = false, version = "1.5.7", features = ["zeroize_derive", "alloc", "serde"] }

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.139"

[target.'cfg(target_family = "windows")'.dependencies]
kernel32-sys = "0.2.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rayon = { default-features = false, version = "1.6.1" }
sysinfo = { default-features = false, version = "0.28.0" }
num_cpus = { default-features = false, version = "1.15.0" }

[dev-dependencies]
citadel_logging = { path = "../citadel_logging", version = "0.4.0" }
rstest = "0.16.0"


[lib]
doctest = false
