name: Saber
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 992
length-ciphertext: 1088
length-secret-key: 2304
length-shared-secret: 32
nistkat-sha256: c9e2c16f41f162c607a1d5704107159e5e12713b9bb8c356b1d68b216e79096e
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/commit/14ede83f1ff3bcc41f0464543542366c68b55871
