[package]
name = "citadel_sdk"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE-COMMERCIAL-USE.pdf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["filesystem", "std"]
filesystem = ["citadel_proto/filesystem", "dirs2"]
multi-threaded = ["citadel_proto/multi-threaded"]
sql = ["citadel_proto/sql"]
redis = ["citadel_proto/redis"]
webrtc = ["citadel_proto/webrtc"]

std = ["citadel_proto/std"]
wasm = ["citadel_proto/wasm"]
google-services = ["citadel_proto/google-services"]

# for testing only
localhost-testing = ["citadel_proto/localhost-testing", "tracing", "citadel_logging"]
localhost-testing-assert-no-proxy = ["citadel_proto/localhost-testing-assert-no-proxy"]
localhost-testing-loopback-only = ["citadel_proto/localhost-testing-loopback-only"]

[dependencies]
citadel_proto = { path = "../citadel_proto", default-features = false }
tokio = { version = "1.23.0", default-features = false, features = [] }
futures = { version = "0.3.16", default-features = false }
parking_lot = "0.12.0"
log = "0.4.8"
lazy_static = "1.4.0"
uuid = { version = "1.0.0", features = ["v4"] }
dirs2 = { version = "3.0.1", optional = true }
tracing = { git = "https://github.com/tokio-rs/tracing.git", branch = "v0.1.x", optional = true }
citadel_logging = { path = "../citadel_logging", version = "0.1.0", optional = true }

[dev-dependencies]
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
dirs2 = "3.0.1"
citadel_logging = { path = "../citadel_logging", version = "0.1.0" }
rstest = "0.16.0"
serde = { version = "1.0.137", features = ["derive"] }
rand = "0.8.5"

[lib]
doctest = false

[package.metadata.cargo-all-features]
# Features "foo" and "bar" are incompatible, so skip permutations including them
skip_feature_sets = [
    ["std", "wasm"],
]

allowlist = ["std", "filesystem", "google-services", "multi-threaded", "sql", "redis", "webrtc"]