name: Kyber512-90s
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 800
length-ciphertext: 736
length-secret-key: 1632
length-shared-secret: 32
nistkat-sha256: d081dafce242de5d2a9b1cfe2b304cf5ebaed71b7a91f028fefd569693307d45
principal-submitters:
  - Peter Schwabe
auxiliary-submitters:
  - Roberto Avanzi
  - Joppe Bos
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Vadim Lyubashevsky
  - John M. Schanck
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/kyber/commit/46e283ab575ec92dfe82fb12229ae2d9d6246682
    - name: avx2
      version: https://github.com/pq-crystals/kyber/commit/46e283ab575ec92dfe82fb12229ae2d9d6246682
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
          required_flags:
            - aes
            - avx2
            - bmi2
            - popcnt
