name: Code coverage

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  coverage:
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--timeout 3600 --packages lusna_sdk --features localhost-testing'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      - uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: codecov.xml