name: Build docs
on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  # 40 MiB stack
  RUST_MIN_STACK: 40971520
  RUST_LOG: "lusna=warn"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: macos-latest
    timeout-minutes: 80
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup toolchain install stable --component llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Run llvm-cov nextest
        env:
          SKIP_EXT_BACKENDS: "true"
        run: cargo llvm-cov nextest --features=filesystem,localhost-testing,multi-threaded --package lusna_sdk,hyxe_user,hyxe_crypt,ez_pqcrypto,hyxe_wire,netbeam,async_ip --lcov --output-path lcov.info
      - uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
  docs:
    needs:
      - coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --package lusna_sdk --features webrtc --no-deps

      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: target/doc
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3.0.2
        if: success()
        with:
          ref: gh-pages
      - name: Ensure valid redirection
        run: |
          mv ${GITHUB_WORKSPACE}/lusna_sdk ${GITHUB_WORKSPACE}/docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=docs\">" > ${GITHUB_WORKSPACE}/index.html
          git config --global user.name "tbraun96"
          git config --global user.email "thomas.braun@avarok.net"
          git add .
          git commit -m "redirection config"
          git push
