name: Build docs
on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  # 40 MiB stack
  RUST_MIN_STACK: 40971520
  RUST_LOG: "lusna"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    env:
      TESTING_SQL_SERVER_ADDR_SERVER: "mysql://root:password@localhost/hyxewave,postgres://nologik:password@localhost/hyxewave,sqlite://file:/home/runner/hyxewave.db,redis://127.0.0.1:6379/1"
      TESTING_SQL_SERVER_ADDR_CLIENT: "mysql://root:password@localhost/hyxewave2,postgres://nologik:password@localhost/hyxewave2,sqlite://file:/home/runner/hyxewave2.db,redis://127.0.0.1:6379/2"
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
      - uses: Avarok-Cybersecurity/gh-actions-deps@alpha04
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: 'password'
      - name: Setup Postgres database (1)
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: latest
          app_user: nologik
          app_user_password: password
          app_db: hyxewave hyxewave2
      - name: Add mysql databases
        run: mysql -uroot -h127.0.0.1 -ppassword -e 'CREATE DATABASE hyxewave; CREATE DATABASE hyxewave2;'
      - name: Augment connection size for psql
        run:  psql -c 'ALTER SYSTEM SET max_connections TO 1000' postgresql://postgres:postgres@localhost/hyxewave && psql -c 'ALTER SYSTEM SET max_connections TO 1000' postgresql://postgres:postgres@localhost/hyxewave2
      - name: Add sqlite databases
        run: touch /home/runner/hyxewave.db && touch /home/runner/hyxewave2.db
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 4
          redis-port: 6379
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run cargo-tarpaulin
        run: 'cargo tarpaulin --timeout 4800 --packages lusna_sdk,hyxe_user,hyxe_crypt,ez_pqcrypto,hyxe_wire,netbeam --features=redis,sql,localhost-testing,multi-threaded -- --test-threads=1 --skip argon_autotuner'
      - uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
  docs:
    needs:
      - coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --package lusna_sdk --features webrtc --no-deps

      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: target/doc
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3.0.2
        if: success()
        with:
          ref: gh-pages
      - name: Ensure valid redirection
        run: |
          mv ${GITHUB_WORKSPACE}/lusna_sdk ${GITHUB_WORKSPACE}/docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=docs\">" > ${GITHUB_WORKSPACE}/index.html
          git config --global user.name "tbraun96"
          git config --global user.email "thomas.braun@avarok.net"
          git add .
          git commit -m "redirection config"
          git push
