on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

name: Publish documentation

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    env:
      # 20 MiB stack
      RUST_MIN_STACK: 20971520

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: doc
          args: --package lusna_sdk --features webrtc --no-deps

      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          build_dir: target/doc
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Ensure valid redirection
        run: | 
          git checkout gh-pages
          touch ${GITHUB_WORKSPACE}/index.html
          echo "<meta http-equiv="refresh" content="0; url=lusna_sdk">" > ${GITHUB_WORKSPACE}/index.html
          git config --global user.name "tbraun96"
          git config --global user.email "thomas.braun@avarok.net"
          git commit -am "Auto update"
          git push
