name: Execute Pipeline
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
jobs:
  workflow:
    name: Validate PR
    uses: ./.github/workflows/validate.yml
