name: Ratchet Stability Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_MIN_STACK: 40971520
  RUST_LOG: "citadel=warn"

jobs:
  stability-test:
    name: Ratchet Stability Test
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Avarok-Cybersecurity/gh-actions-deps@master
      - uses: taiki-e/install-action@nextest
      - name: Run ratchet stability test
        run: cargo make ratchet-stability-test